#!/bin/bash

echo "📊 ADA Competitive Analysis Presentation Deck"
echo "============================================="
echo "✅ Competitive analysis deck file found"
echo "🚀 Starting presentation deck on port 8505..."
echo ""
echo "📋 Presentation Instructions:"
echo "1. Wait for deck to load (http://localhost:8505)"
echo "2. Use the sidebar to navigate through slides:"
echo "   - 🏠 Executive Summary"
echo "   - 📈 Performance Comparison"
echo "   - 🎯 Radar Chart Analysis"
echo "   - 📋 Feature Comparison"
echo "   - 💰 Cost Analysis"
echo "   - 🚀 Competitive Advantages"
echo "   - 📊 Market Positioning"
echo "   - 🎯 Recommendations"
echo "3. Each slide shows interactive charts and analysis"
echo "4. Perfect for board presentations or investor meetings"
echo ""
echo "🎯 Presentation URL: http://localhost:8505"
echo "⏱️  Duration: 15-20 minutes presentation"
echo "📱 Format: Interactive web-based slides"
echo ""
echo "Starting Streamlit competitive analysis deck..."
echo "Press Ctrl+C to stop the presentation"

python3 -m streamlit run ADA_Competitive_Analysis_Deck.py --server.port 8505 --server.address localhost 